/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 crystal.glb
Author: Ken (https://sketchfab.com/kenaiden)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/crystal-fe78a6b8a8dc41e89337ab490c524ce8
Title: Crystal
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { Clock } from 'three'

export function Model(props) {
  const { nodes, materials } = useGLTF('/crystal.glb')

  const ref = useRef();

  useFrame(({ clock }) => {
    ref.current.rotation.z = clock.getElapsedTime()/2;
  });

  return (
    <group {...props} dispose={null}>
      <group  position={[17.01, 0, -9.49]} rotation={[-Math.PI / 2, 0, 0]} scale={0.2}>
        <group  rotation={[Math.PI / 2, 0, 0]}>
          <mesh ref={ref} geometry={nodes.Cone007__0.geometry} material={materials['Scene_-_Root']} position={[-122.22, 34.23, -15.44]} rotation={[Math.PI / 2, 0, -2.71]} scale={10} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/crystal.glb')
