/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 magic_crystal.glb
Author: vitaltime (https://sketchfab.com/deitaurginko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/magic-crystal-7da36ddc2a28494586269bca7d4a7942
Title: Magic Crystal
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Model(props) {
  const { nodes, materials } = useGLTF('/magic_crystal.glb')
  const ref = useRef()
  useFrame(({clock}) => {
    ref.current.rotation.y=clock.getElapsedTime()/2;
  })
  return (
    <group ref={ref} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials['default']} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}
