/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 the_penrose_triangle.glb
Author: tamminen (https://sketchfab.com/tamminen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-penrose-triangle-a1dacb7370eb40d48c7a48f34d91142b
Title: The Penrose Triangle
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/penrose_triangle.glb')
  return (
    <group {...props} dispose={null} scale={0.2} position={[0,-0.8,0]}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} rotation={[0, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/penrose_triangle.glb')
