/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 penrose_object.glb
Author: bomi1337 (https://sketchfab.com/bomi1337)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/penrose-object-d12687bea0f941cdb0f310a940c1b751
Title: Penrose Object
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Model(props) {
  const { nodes, materials } = useGLTF("/penrose_object.glb");
  const ref=useRef();
  useFrame(({clock}) => {
    console.log(ref.current.rotation);
  })

  return (
    <group ref={ref} {...props} dispose={null} scale={1} position={[0, 0, 0]}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials["Scene_-_Root"]}
        rotation={[-Math.PI / 4,  0, Math.PI*2 / 3]}
      />
    </group>
  );
}

useGLTF.preload("/penrose_object.glb");
