/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 untitled.glb
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import { useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials,animations } = useGLTF('/Rocket_3d.glb')
  const {actions,names} = useAnimations(animations,group)
  console.log(names)
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, -219.75, 0]} scale={[1.2, 1, 1.2]}>
          <mesh geometry={nodes.Lathe_2.geometry} material={nodes.Lathe_2.material} scale={[1.5, 2.05, 1.5]} />
          <mesh geometry={nodes.Lathe.geometry} material={nodes.Lathe.material} scale={[1.2, 1.64, 1.2]} />
        </group>
        <group position={[1.05, -15.9, -1.5]}>
          <mesh geometry={nodes.mesh_6_instance_0.geometry} material={nodes.mesh_6_instance_0.material} position={[38, 0, 0]} />
          <mesh geometry={nodes.mesh_6_instance_1.geometry} material={nodes.mesh_6_instance_1.material} position={[0, 0, 38]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.mesh_6_instance_2.geometry} material={nodes.mesh_6_instance_2.material} position={[-38, 0, 0]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_6_instance_3.geometry} material={nodes.mesh_6_instance_3.material} position={[0, 0, -38]} rotation={[0, Math.PI / 2, 0]} />
        </group>
        <pointLight intensity={1} decay={2} distance={2000} position={[0, -183.19, 0]} />
        <directionalLight intensity={5} decay={2} rotation={[-0.51, 0.63, 0.76]} />
        <PerspectiveCamera makeDefault={false} far={100000} near={70} fov={45} position={[-139.56, 51.11, 646.56]} rotation={[-0.08, -0.21, -0.02]} />
        <mesh geometry={nodes.Cockpit.geometry} material={nodes.Cockpit.material} position={[0, 74.95, 19.13]} scale={0.5} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={nodes.Cylinder_2.material} position={[0, -119.57, 0]} scale={1.3} />
        <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[0, -112.34, 0]} scale={1.3} />
        <mesh geometry={nodes.Body.geometry} material={nodes.Body.material} position={[-1, 0, 0]} scale={3} />
      </group>
    </group>
  )
}

useGLTF.preload('/Rocket_3d.glb')
